package edu.eg.csed.mans.chess.Logic;

public enum ChessBoardFlags {
    ERROR_MOVEMENT_OVER_OTHER_PIECE,
    ERROR_MOVEMENT_OVER_SAME_PLAYER,
    ERROR_MOVEMENT_THREATS_KING,

    ERROR_L3_MOVEMENT_ISNOT_EFFECIENT,
    ERROR_L3_MOVEMENT_THREATS_KING,
}
